/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as DownloadOfflineRouteImport } from './routes/download-offline'
import { Route as ExportKitRouteImport } from './routes/export-kit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiClassroomSaveRouteImport } from './routes/api/classroom-save'
import { Route as ApiExportPortableRouteImport } from './routes/api/export-portable'
import { Route as ApiPackDownloadRouteImport } from './routes/api/pack-download'
import { Route as ClassClassIdRouteImport } from './routes/class/$classId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ClassClassIdIndexRouteImport } from './routes/class/$classId/index'
import { Route as ClassClassIdReportsRouteImport } from './routes/class/$classId/reports'
import { Route as ClassClassIdSettingsRouteImport } from './routes/class/$classId/settings'
import { Route as ClassClassIdStudentStudentIdRouteImport } from './routes/class/$classId/student/$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadOfflineRoute = DownloadOfflineRouteImport.update({
  id: '/download-offline',
  path: '/download-offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportKitRoute = ExportKitRouteImport.update({
  id: '/export-kit',
  path: '/export-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassroomSaveRoute = ApiClassroomSaveRouteImport.update({
  id: '/api/classroom-save',
  path: '/api/classroom-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportPortableRoute = ApiExportPortableRouteImport.update({
  id: '/api/export-portable',
  path: '/api/export-portable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackDownloadRoute = ApiPackDownloadRouteImport.update({
  id: '/api/pack-download',
  path: '/api/pack-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdRoute = ClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdIndexRoute = ClassClassIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassClassIdRoute,
} as any)
const ClassClassIdReportsRoute = ClassClassIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ClassClassIdRoute,
} as any)
const ClassClassIdSettingsRoute = ClassClassIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClassClassIdRoute,
} as any)
const ClassClassIdStudentStudentIdRoute =
  ClassClassIdStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => ClassClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/download-offline': typeof DownloadOfflineRoute
  '/export-kit': typeof ExportKitRoute
  '/login': typeof LoginRoute
  '/api/classroom-save': typeof ApiClassroomSaveRoute
  '/api/export-portable': typeof ApiExportPortableRoute
  '/api/pack-download': typeof ApiPackDownloadRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/class/$classId/reports': typeof ClassClassIdReportsRoute
  '/class/$classId/settings': typeof ClassClassIdSettingsRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/student/$studentId': typeof ClassClassIdStudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/download-offline': typeof DownloadOfflineRoute
  '/export-kit': typeof ExportKitRoute
  '/login': typeof LoginRoute
  '/api/classroom-save': typeof ApiClassroomSaveRoute
  '/api/export-portable': typeof ApiExportPortableRoute
  '/api/pack-download': typeof ApiPackDownloadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/class/$classId/reports': typeof ClassClassIdReportsRoute
  '/class/$classId/settings': typeof ClassClassIdSettingsRoute
  '/class/$classId': typeof ClassClassIdIndexRoute
  '/class/$classId/student/$studentId': typeof ClassClassIdStudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/download-offline': typeof DownloadOfflineRoute
  '/export-kit': typeof ExportKitRoute
  '/login': typeof LoginRoute
  '/api/classroom-save': typeof ApiClassroomSaveRoute
  '/api/export-portable': typeof ApiExportPortableRoute
  '/api/pack-download': typeof ApiPackDownloadRoute
  '/class/$classId': typeof ClassClassIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/class/$classId/reports': typeof ClassClassIdReportsRoute
  '/class/$classId/settings': typeof ClassClassIdSettingsRoute
  '/class/$classId/': typeof ClassClassIdIndexRoute
  '/class/$classId/student/$studentId': typeof ClassClassIdStudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived'
    | '/download-offline'
    | '/export-kit'
    | '/login'
    | '/api/classroom-save'
    | '/api/export-portable'
    | '/api/pack-download'
    | '/class/$classId'
    | '/api/auth/$'
    | '/class/$classId/reports'
    | '/class/$classId/settings'
    | '/class/$classId/'
    | '/class/$classId/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/download-offline'
    | '/export-kit'
    | '/login'
    | '/api/classroom-save'
    | '/api/export-portable'
    | '/api/pack-download'
    | '/api/auth/$'
    | '/class/$classId/reports'
    | '/class/$classId/settings'
    | '/class/$classId'
    | '/class/$classId/student/$studentId'
  id:
    | '__root__'
    | '/'
    | '/archived'
    | '/download-offline'
    | '/export-kit'
    | '/login'
    | '/api/classroom-save'
    | '/api/export-portable'
    | '/api/pack-download'
    | '/class/$classId'
    | '/api/auth/$'
    | '/class/$classId/reports'
    | '/class/$classId/settings'
    | '/class/$classId/'
    | '/class/$classId/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  DownloadOfflineRoute: typeof DownloadOfflineRoute
  ExportKitRoute: typeof ExportKitRoute
  LoginRoute: typeof LoginRoute
  ApiClassroomSaveRoute: typeof ApiClassroomSaveRoute
  ApiExportPortableRoute: typeof ApiExportPortableRoute
  ApiPackDownloadRoute: typeof ApiPackDownloadRoute
  ClassClassIdRoute: typeof ClassClassIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-offline': {
      id: '/download-offline'
      path: '/download-offline'
      fullPath: '/download-offline'
      preLoaderRoute: typeof DownloadOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-kit': {
      id: '/export-kit'
      path: '/export-kit'
      fullPath: '/export-kit'
      preLoaderRoute: typeof ExportKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classroom-save': {
      id: '/api/classroom-save'
      path: '/api/classroom-save'
      fullPath: '/api/classroom-save'
      preLoaderRoute: typeof ApiClassroomSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-portable': {
      id: '/api/export-portable'
      path: '/api/export-portable'
      fullPath: '/api/export-portable'
      preLoaderRoute: typeof ApiExportPortableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pack-download': {
      id: '/api/pack-download'
      path: '/api/pack-download'
      fullPath: '/api/pack-download'
      preLoaderRoute: typeof ApiPackDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId': {
      id: '/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId/': {
      id: '/class/$classId/'
      path: '/'
      fullPath: '/class/$classId/'
      preLoaderRoute: typeof ClassClassIdIndexRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
    '/class/$classId/reports': {
      id: '/class/$classId/reports'
      path: '/reports'
      fullPath: '/class/$classId/reports'
      preLoaderRoute: typeof ClassClassIdReportsRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
    '/class/$classId/settings': {
      id: '/class/$classId/settings'
      path: '/settings'
      fullPath: '/class/$classId/settings'
      preLoaderRoute: typeof ClassClassIdSettingsRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
    '/class/$classId/student/$studentId': {
      id: '/class/$classId/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/class/$classId/student/$studentId'
      preLoaderRoute: typeof ClassClassIdStudentStudentIdRouteImport
      parentRoute: typeof ClassClassIdRoute
    }
  }
}

interface ClassClassIdRouteChildren {
  ClassClassIdReportsRoute: typeof ClassClassIdReportsRoute
  ClassClassIdSettingsRoute: typeof ClassClassIdSettingsRoute
  ClassClassIdIndexRoute: typeof ClassClassIdIndexRoute
  ClassClassIdStudentStudentIdRoute: typeof ClassClassIdStudentStudentIdRoute
}

const ClassClassIdRouteChildren: ClassClassIdRouteChildren = {
  ClassClassIdReportsRoute: ClassClassIdReportsRoute,
  ClassClassIdSettingsRoute: ClassClassIdSettingsRoute,
  ClassClassIdIndexRoute: ClassClassIdIndexRoute,
  ClassClassIdStudentStudentIdRoute: ClassClassIdStudentStudentIdRoute,
}

const ClassClassIdRouteWithChildren = ClassClassIdRoute._addFileChildren(
  ClassClassIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedRoute: ArchivedRoute,
  DownloadOfflineRoute: DownloadOfflineRoute,
  ExportKitRoute: ExportKitRoute,
  LoginRoute: LoginRoute,
  ApiClassroomSaveRoute: ApiClassroomSaveRoute,
  ApiExportPortableRoute: ApiExportPortableRoute,
  ApiPackDownloadRoute: ApiPackDownloadRoute,
  ClassClassIdRoute: ClassClassIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
